---
- name: Ajout de la clé GPG Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajout du repository Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Installation de Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: S'assurer que Docker est démarré et activé
  service:
    name: docker
    state: started
    enabled: yes

- name: Ajout de l'utilisateur au groupe docker
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"

- name: Installation de docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'