version: '3.8'

services:
  comprehend-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root s3://mlops-zi98v3lj/mlflow-artifacts --backend-store-uri sqlite:///mlflow.db
    volumes:
      - mlflow_data:/mlflow
    restart: always

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mlflow_data:
  prometheus_data:
  grafana_data: