services:
  comprehend-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
    command: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root s3://mlops-4d3ai81p/mlflow-artifacts --backend-store-uri sqlite:///mlflow.db
    volumes:
      - mlflow_data:/mlflow

volumes:
  mlflow_data: